# Generated by Django 2.2.4 on 2020-01-02 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_userprofile_friends'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0002_friendgroups'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255)),
                ('group_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to='accounts.UserProfile')),
                ('peoples', models.ManyToManyField(blank=True, related_name='peoples', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='FriendGroups',
        ),
    ]
