# Generated by Django 2.2.4 on 2020-01-27 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friends', '0003_auto_20200102_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendgroup',
            old_name='group_admin',
            new_name='FGroup_admin',
        ),
        migrations.RenameField(
            model_name='friendgroup',
            old_name='peoples',
            new_name='FGroup_members',
        ),
        migrations.RenameField(
            model_name='friendgroup',
            old_name='group_name',
            new_name='FGroup_name',
        ),
        migrations.AddField(
            model_name='friendgroup',
            name='FGroup_cr_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendgroup',
            name='FGroup_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='friendgroup',
            name='FGroup_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics/fav_page_img/'),
        ),
        migrations.CreateModel(
            name='FriendGroupPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FGroup_post_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('FGroup_post_write', models.TextField(blank=True, max_length=255, null=True)),
                ('FGroup_post_image', models.ImageField(blank=True, null=True, upload_to='pics/fgroups_content')),
                ('FGroup_post_video', models.FileField(blank=True, null=True, upload_to='videos/fgroups_content')),
                ('FGroup_post_cr_date', models.DateTimeField(auto_now_add=True)),
                ('FGroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.FriendGroup')),
                ('FGroup_post_likes', models.ManyToManyField(blank=True, related_name='fgroup_post_likes', to=settings.AUTH_USER_MODEL)),
                ('FGroup_post_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FGroupPostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FGroup_com_cr_date', models.DateTimeField(auto_now_add=True)),
                ('FGroup_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='friends.FriendGroupPost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FGroupPostComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FGroup_post_comment', models.TextField(blank=True, null=True)),
                ('c_image', models.ImageField(blank=True, null=True, upload_to='pics/fgroups_content')),
                ('cm_cr_date', models.DateTimeField(auto_now_add=True)),
                ('FGroup_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='friends.FriendGroupPost')),
                ('cm_likes', models.ManyToManyField(blank=True, related_name='fgroup_cm_likes', to=settings.AUTH_USER_MODEL)),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
