# Generated by Django 2.2.4 on 2020-01-27 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_auto_20200127_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendgroup',
            name='FGroup_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics/fgroups'),
        ),
    ]
