# Generated by Django 2.2.4 on 2020-01-30 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0005_auto_20200127_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friendgrouppost',
            old_name='FGroup_post_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='friendgrouppost',
            old_name='FGroup_post_cr_date',
            new_name='post_cr_date',
        ),
        migrations.RenameField(
            model_name='friendgrouppost',
            old_name='FGroup_post_image',
            new_name='post_image',
        ),
        migrations.RenameField(
            model_name='friendgrouppost',
            old_name='FGroup_post_subject',
            new_name='post_subject',
        ),
        migrations.RenameField(
            model_name='friendgrouppost',
            old_name='FGroup_post_video',
            new_name='post_video',
        ),
        migrations.RenameField(
            model_name='friendgrouppost',
            old_name='FGroup_post_write',
            new_name='post_write',
        ),
        migrations.RenameField(
            model_name='friendgrouppost',
            old_name='FGroup_post_uploaded_by',
            new_name='uploaded_by',
        ),
    ]
