# Generated by Django 2.2.4 on 2020-01-08 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_userprofile_friends'),
        ('olympus', '0024_remove_userpost_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouritePages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fav_page_name', models.TextField()),
                ('fav_page_cr_date', models.DateTimeField(auto_now_add=True)),
                ('fav_page_members', models.ManyToManyField(blank=True, related_name='fav_page_members', to=settings.AUTH_USER_MODEL)),
                ('fav_page_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
