# Generated by Django 2.2.4 on 2020-01-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0026_userfavouritepages'),
    ]

    operations = [
        migrations.AddField(
            model_name='favouritepages',
            name='fav_page_desc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='favouritepages',
            name='fva_page_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics/fav_page_img'),
        ),
    ]
