# Generated by Django 2.2.4 on 2020-01-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0027_auto_20200110_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favouritepages',
            name='fva_page_img',
            field=models.ImageField(blank=True, null=True, upload_to='pics/fav_page_img/'),
        ),
    ]
