# Generated by Django 2.2.4 on 2020-01-16 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympus', '0028_auto_20200110_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavPagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favpage_post_subject', models.CharField(blank=True, max_length=255, null=True)),
                ('favpage_post_write', models.TextField(blank=True, max_length=255, null=True)),
                ('favpage_post_image', models.ImageField(blank=True, null=True, upload_to='pics/fav_pages_content')),
                ('favpage_post_video', models.FileField(blank=True, null=True, upload_to='videos/fav_pages_content')),
                ('favpage_post_cr_date', models.DateTimeField(auto_now_add=True)),
                ('favpage_likes', models.ManyToManyField(blank=True, related_name='favpage_likes', to=settings.AUTH_USER_MODEL)),
                ('favpage_post_uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='FavPagePostUserComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favpage_post_comment', models.TextField(blank=True, null=True)),
                ('c_image', models.ImageField(blank=True, null=True, upload_to='pics/fav_pages_content')),
                ('cm_cr_date', models.DateTimeField(auto_now_add=True)),
                ('cm_likes', models.ManyToManyField(blank=True, related_name='favpage_cm_likes', to=settings.AUTH_USER_MODEL)),
                ('comment_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olympus.FavPagePost')),
            ],
        ),
        migrations.CreateModel(
            name='FavPagePostLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favpage_com_cr_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympus.FavPagePost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
    ]
