# Generated by Django 2.2.4 on 2020-01-17 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0029_favpagepost_favpagepostlike_favpagepostusercomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='favpagepost',
            name='fav_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olympus.FavouritePages'),
        ),
        migrations.AlterField(
            model_name='favpagepost',
            name='favpage_post_uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
