# Generated by Django 2.2.4 on 2020-01-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0030_auto_20200117_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favpagepost',
            name='favpage_post_uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile'),
        ),
    ]
