# Generated by Django 2.2.4 on 2020-01-23 12:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('olympus', '0031_auto_20200117_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='favpagepost',
            name='favpage_post_comments',
            field=models.ManyToManyField(blank=True, related_name='favpage_post_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
