# Generated by Django 2.2.4 on 2020-01-30 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympus', '0033_auto_20200130_1357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favpagepost',
            old_name='favpage_post_comments',
            new_name='comments',
        ),
        migrations.RenameField(
            model_name='favpagepost',
            old_name='favpage_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='favpagepost',
            old_name='favpage_post_cr_date',
            new_name='post_cr_date',
        ),
        migrations.RenameField(
            model_name='favpagepost',
            old_name='favpage_post_image',
            new_name='post_image',
        ),
        migrations.RenameField(
            model_name='favpagepost',
            old_name='favpage_post_subject',
            new_name='post_subject',
        ),
        migrations.RenameField(
            model_name='favpagepost',
            old_name='favpage_post_video',
            new_name='post_video',
        ),
        migrations.RenameField(
            model_name='favpagepost',
            old_name='favpage_post_write',
            new_name='post_write',
        ),
        migrations.RenameField(
            model_name='favpagepost',
            old_name='favpage_post_uploaded_by',
            new_name='uploaded_by',
        ),
    ]
